# Generated by Django 4.2.20 on 2025-03-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_app', '0004_book_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('meaning', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meaning')),
                ('example', models.CharField(blank=True, max_length=200, null=True, verbose_name='Example')),
                ('status', models.CharField(choices=[('m', 'memorized'), ('l', 'learning'), ('f', 'forgot')], default='l', help_text='Study Status', max_length=1)),
                ('category', models.CharField(blank=True, choices=[('n', 'noun'), ('v', 'verb'), ('adj', 'adjective'), ('adv', 'adverb'), ('prep', 'preposition'), ('conj', 'conjunction'), ('pron', 'pronoun'), ('int', 'interjection')], help_text='Word Class', max_length=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
