# Generated by Django 4.2.20 on 2025-03-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_app', '0005_vocab_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='The time the vocab was created.', null=True),
        ),
    ]
