# Generated by Django 4.2.20 on 2025-03-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_app', '0006_vocab_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='category',
            field=models.CharField(blank=True, choices=[('n', 'Noun'), ('v', 'Verb'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('prep', 'Preposition'), ('conj', 'Conjunction'), ('pron', 'Pronoun'), ('int', 'Interjection')], help_text='Word Class', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='The date the vocab was created.', null=True),
        ),
    ]
