# Generated by Django 4.2.20 on 2025-04-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_app', '0009_alter_vocab_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocab',
            name='user',
        ),
    ]
