# Generated by Django 4.2.20 on 2025-04-08 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test_app', '0010_remove_vocab_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
